version: "3.8"

services:

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - creditnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - creditnet

networks:
  creditnet:
    driver: bridge
